apiVersion: v1
kind: ReplicationController
metadata:
  name: node-app-green
spec:
  replicas: 1
  selector:
    app: node-app-green
  template:
    metadata:
      name: node-app-green
      labels:
        app: node-app-green
    spec:
      containers:
      - name: node-app-green
        image: docker.io/rdwns/node-docker-green
        ports:
        - containerPort: 8080