apiVersion: v1
kind: ReplicationController
metadata:
  name: node-app-blue
spec:
  replicas: 1
  selector:
    app: node-app-blue
  template:
    metadata:
      name: node-app-blue
      labels:
        app: node-app-blue
    spec:
      containers:
      - name: node-app-blue
        image: docker.io/rdwns/node-docker-blue
        ports:
        - containerPort: 8080